import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../widgets/auth/auth_form.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class AuthScreen extends StatefulWidget {
  const AuthScreen({super.key});

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _auth = FirebaseAuth.instance;
  var _isLoading = false;

  void _submitAuthForm(
    String email,
    String password,
    String username,
    bool isLogin,
    BuildContext authFormContext,
  ) async {
    UserCredential authResult;
    try {
      setState(() {
        _isLoading = true;
      });
      if (isLogin) {
        authResult = await _auth.signInWithEmailAndPassword(
            email: email, password: password);
      } else {
        authResult = await _auth.createUserWithEmailAndPassword(
            email: email, password: password);
      }
      await FirebaseFirestore.instance
          .collection('users')
          .doc(authResult.user?.uid) // user id generated by firebase
          .set({
        'username': username,
        'email': email
      }); // create data through a map -> returns a future so can use await
    } on PlatformException catch (err) {
      setState(() {
        _isLoading = false;
      });

      var errMsg = 'An error occurred, please check your email and password.';
      if (err.message != null) {
        errMsg = err.message as String;
      }
      print(errMsg);

      // Scaffold.of(authFormContext).showBottomSheet((context) {
      //   return SnackBar(
      //     content: Text(errMsg),
      //     backgroundColor: Theme.of(authFormContext).colorScheme.error,
      //   );
      // });
    } catch (err) {
      setState(() {
        _isLoading = false;
      });
      // Scaffold.of(authFormContext)
      //     .showBottomSheet((authFormContext) => SnackBar(
      //           content: Text(err.toString()),
      //           backgroundColor: Theme.of(authFormContext).colorScheme.error,
      //         ));
      print(err);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      body: AuthForm(_submitAuthForm, _isLoading),
    );
  }
}
